### ISSUE TITLE
Sending tokens doesn't work

### ISSUE THREAD

**Issue by ShazerHD** [Icesofty/Digital-Currency#14]
I've just set this up and now sending tokens won't work.

It says that I don't have enough tokens even when I do.

I've added in a check to see what was the problem:
`  .post((req, res) => {
    console.log("1. " + req.body.receiver !== req.user.username);
    console.log("2. " +req.body.amount <=req.user.tokens);
    console.log("3. " + Number(req.body.amount) > 0);
    console.log("4. " + Number.isInteger(req.body.amount));`

That returns 
`true
false
false
4. false`
but all of them should be true based on what I put into the send fields.

Any ideas?

**Comment by Icesofty** [comment]
Hi @ShazerHD , thanks for your feedback. 
Can you try to change the line 219? 

From 
```
Number(req.body.amount) > 0 &&
      Number.isInteger(req.body.amount)
```
To 
`Number(req.body.amount) > 0`

Looks like my last commit broke the logic

**Comment by Icesofty** [comment]
Fixed with https://github.com/Icesofty/Digital-Currency/commit/47e0e8f176cdcc08dd649e6d0d09eeb7bce3bf0b
