### ISSUE TITLE
is this still in development?

### ISSUE THREAD

**Issue by 17lwinn** [Icesofty/Digital-Currency#17]
Hi! this is such a great project- is it still being developed?

**Comment by Icesofty** [comment]
Hi, 

This project is stable right now, 
But yes this is still in development, I'm just too focused on another project right now (https://french.dev)

**Comment by 17lwinn** [comment]
Okay! :)

**Comment by 17lwinn** [comment]
Okay! :)

**Comment by 17lwinn** [comment]
Okay! :)

**Comment by 17lwinn** [comment]
Okay! :)

**Comment by 17lwinn** [comment]
Okay! :)

**Comment by 17lwinn** [comment]
Okay!

**Comment by 17lwinn** [comment]
Okay!

**Comment by 17lwinn** [comment]
Okay!

**Comment by 17lwinn** [comment]
Okay!

**Comment by 17lwinn** [comment]
Okay!

**Comment by Jonyk56** [comment]
What the?

**Comment by ghost** [comment]
Okay!
