### ISSUE TITLE
Token Decimal Value

### ISSUE THREAD

**Issue by Jamie96ITS** [Icesofty/Digital-Currency#9]
Currently, token decimal value (1, 1.01, 1.11, 1.1111) is handled only by HTML5 Number validation. 

By default, on supported browsers, this results on a restriction of Tokens being worth only whole numbers. However, on unsupported browsers(old iOS devices, for example), this validation is not performed, allowing for partial token transfers. 

Token value validation should be handled by the main app logic. This will allow for configurable token decimal value(do I want a whole number currency? Or do I want something that mirrors real word currency with partial values? Switch a variable.) while also preventing unexpected edge cases where an unsupported browser reverts it to a text entry field and allows sending of 1.00021 tokens that  can't be moved around by HTML5 browsers. 

Alternatively, or in conjunction with main app logic, add the "step" flag to the number field of send.ejs and set to "any", .01, or a variable to allow HTML5 browsers to have the same fun as not.

**Comment by Icesofty** [comment]
Hey @Jamie96ITS ,
Sorry for the late reply.
Didn't get a notification for this issue. 

For now, I'm more focused on my other Go blockchain project. (https://github.com/Icesofty/Oracle-Agent), I'll try to improve that issue ASAP.

Thanks

**Comment by Icesofty** [comment]
https://github.com/Icesofty/Digital-Currency/commit/5d5c887f6235fa5a0e66af15d4e4b4bdab91ba1e

Fixed the issue
